// <auto-generated />
using MLRecommendator.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MLRecommendator.Database.Migrations
{
    [DbContext(typeof(MalContext))]
    [Migration("20220531213938_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("MLRecommendator.Database.Models.Anime", b =>
                {
                    b.Property<long>("SeriesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("SeriesId"));

                    b.Property<float>("Action")
                        .HasColumnType("real");

                    b.Property<float>("AdultCast")
                        .HasColumnType("real");

                    b.Property<float>("Adventure")
                        .HasColumnType("real");

                    b.Property<float>("Anthropomorphic")
                        .HasColumnType("real");

                    b.Property<float>("AvantGarde")
                        .HasColumnType("real");

                    b.Property<int>("AverageEpisodeDuration")
                        .HasColumnType("integer");

                    b.Property<float>("AwardWinning")
                        .HasColumnType("real");

                    b.Property<float>("BoysLove")
                        .HasColumnType("real");

                    b.Property<float>("CGDCT")
                        .HasColumnType("real");

                    b.Property<float>("Childcare")
                        .HasColumnType("real");

                    b.Property<float>("CombatSports")
                        .HasColumnType("real");

                    b.Property<float>("Comedy")
                        .HasColumnType("real");

                    b.Property<float>("Crossdressing")
                        .HasColumnType("real");

                    b.Property<float>("Delinquents")
                        .HasColumnType("real");

                    b.Property<float>("Detective")
                        .HasColumnType("real");

                    b.Property<float>("Drama")
                        .HasColumnType("real");

                    b.Property<float>("Ecchi")
                        .HasColumnType("real");

                    b.Property<float>("Educational")
                        .HasColumnType("real");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("integer");

                    b.Property<float>("Erotica")
                        .HasColumnType("real");

                    b.Property<float>("Fantasy")
                        .HasColumnType("real");

                    b.Property<float>("GagHumor")
                        .HasColumnType("real");

                    b.Property<string>("Genres")
                        .HasColumnType("text");

                    b.Property<float>("GirlsLove")
                        .HasColumnType("real");

                    b.Property<float>("Gore")
                        .HasColumnType("real");

                    b.Property<float>("Gourmet")
                        .HasColumnType("real");

                    b.Property<float>("Harem")
                        .HasColumnType("real");

                    b.Property<float>("Hentai")
                        .HasColumnType("real");

                    b.Property<float>("HighStakesGame")
                        .HasColumnType("real");

                    b.Property<float>("Historical")
                        .HasColumnType("real");

                    b.Property<float>("Horror")
                        .HasColumnType("real");

                    b.Property<float>("IdolsFemale")
                        .HasColumnType("real");

                    b.Property<float>("IdolsMale")
                        .HasColumnType("real");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<float>("Isekai")
                        .HasColumnType("real");

                    b.Property<float>("Iyashikei")
                        .HasColumnType("real");

                    b.Property<float>("Josei")
                        .HasColumnType("real");

                    b.Property<float>("Kids")
                        .HasColumnType("real");

                    b.Property<float>("LovePolygon")
                        .HasColumnType("real");

                    b.Property<float>("MagicalSexShift")
                        .HasColumnType("real");

                    b.Property<float>("MahouShoujo")
                        .HasColumnType("real");

                    b.Property<float>("MartialArts")
                        .HasColumnType("real");

                    b.Property<float>("Mean")
                        .HasColumnType("real");

                    b.Property<float>("Mecha")
                        .HasColumnType("real");

                    b.Property<float>("Medical")
                        .HasColumnType("real");

                    b.Property<float>("Military")
                        .HasColumnType("real");

                    b.Property<float>("Music")
                        .HasColumnType("real");

                    b.Property<float>("Mystery")
                        .HasColumnType("real");

                    b.Property<float>("Mythology")
                        .HasColumnType("real");

                    b.Property<string>("Nsfw")
                        .HasColumnType("text");

                    b.Property<float>("OrganizedCrime")
                        .HasColumnType("real");

                    b.Property<float>("OtakuCulture")
                        .HasColumnType("real");

                    b.Property<float>("Parody")
                        .HasColumnType("real");

                    b.Property<float>("PerformingArts")
                        .HasColumnType("real");

                    b.Property<float>("Pets")
                        .HasColumnType("real");

                    b.Property<long>("Popularity")
                        .HasColumnType("bigint");

                    b.Property<float>("Psychological")
                        .HasColumnType("real");

                    b.Property<float>("Racing")
                        .HasColumnType("real");

                    b.Property<long>("Rank")
                        .HasColumnType("bigint");

                    b.Property<string>("Rating")
                        .HasColumnType("text");

                    b.Property<float>("Reincarnation")
                        .HasColumnType("real");

                    b.Property<float>("ReverseHarem")
                        .HasColumnType("real");

                    b.Property<float>("Romance")
                        .HasColumnType("real");

                    b.Property<float>("RomanticSubtext")
                        .HasColumnType("real");

                    b.Property<float>("Samurai")
                        .HasColumnType("real");

                    b.Property<float>("School")
                        .HasColumnType("real");

                    b.Property<float>("SciFi")
                        .HasColumnType("real");

                    b.Property<float>("Seinen")
                        .HasColumnType("real");

                    b.Property<float>("Shoujo")
                        .HasColumnType("real");

                    b.Property<float>("Shounen")
                        .HasColumnType("real");

                    b.Property<float>("Showbiz")
                        .HasColumnType("real");

                    b.Property<float>("SliceOfLife")
                        .HasColumnType("real");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<float>("Space")
                        .HasColumnType("real");

                    b.Property<float>("Sports")
                        .HasColumnType("real");

                    b.Property<string>("StartDate")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<float>("StrategyGame")
                        .HasColumnType("real");

                    b.Property<string>("Studios")
                        .HasColumnType("text");

                    b.Property<float>("SuperPower")
                        .HasColumnType("real");

                    b.Property<float>("Supernatural")
                        .HasColumnType("real");

                    b.Property<float>("Survival")
                        .HasColumnType("real");

                    b.Property<float>("Suspense")
                        .HasColumnType("real");

                    b.Property<string>("Synopsis")
                        .HasColumnType("text");

                    b.Property<float>("TeamSports")
                        .HasColumnType("real");

                    b.Property<float>("TimeTravel")
                        .HasColumnType("real");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<long>("UsersNumber")
                        .HasColumnType("bigint");

                    b.Property<long>("UsersScoringNumber")
                        .HasColumnType("bigint");

                    b.Property<float>("Vampire")
                        .HasColumnType("real");

                    b.Property<float>("VideoGame")
                        .HasColumnType("real");

                    b.Property<float>("VisualArts")
                        .HasColumnType("real");

                    b.Property<float>("Workplace")
                        .HasColumnType("real");

                    b.HasKey("SeriesId");

                    b.ToTable("Animes");
                });

            modelBuilder.Entity("MLRecommendator.Database.Models.UserScoring", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<float>("Action")
                        .HasColumnType("real");

                    b.Property<float>("AdultCast")
                        .HasColumnType("real");

                    b.Property<float>("Adventure")
                        .HasColumnType("real");

                    b.Property<float>("Anthropomorphic")
                        .HasColumnType("real");

                    b.Property<float>("AvantGarde")
                        .HasColumnType("real");

                    b.Property<float>("AwardWinning")
                        .HasColumnType("real");

                    b.Property<float>("BoysLove")
                        .HasColumnType("real");

                    b.Property<float>("CGDCT")
                        .HasColumnType("real");

                    b.Property<float>("Childcare")
                        .HasColumnType("real");

                    b.Property<float>("CombatSports")
                        .HasColumnType("real");

                    b.Property<float>("Comedy")
                        .HasColumnType("real");

                    b.Property<float>("Crossdressing")
                        .HasColumnType("real");

                    b.Property<float>("Delinquents")
                        .HasColumnType("real");

                    b.Property<float>("Detective")
                        .HasColumnType("real");

                    b.Property<float>("Drama")
                        .HasColumnType("real");

                    b.Property<float>("Ecchi")
                        .HasColumnType("real");

                    b.Property<float>("Educational")
                        .HasColumnType("real");

                    b.Property<float>("Erotica")
                        .HasColumnType("real");

                    b.Property<float>("Fantasy")
                        .HasColumnType("real");

                    b.Property<float>("GagHumor")
                        .HasColumnType("real");

                    b.Property<float>("GirlsLove")
                        .HasColumnType("real");

                    b.Property<float>("Gore")
                        .HasColumnType("real");

                    b.Property<float>("Gourmet")
                        .HasColumnType("real");

                    b.Property<float>("Harem")
                        .HasColumnType("real");

                    b.Property<float>("Hentai")
                        .HasColumnType("real");

                    b.Property<float>("HighStakesGame")
                        .HasColumnType("real");

                    b.Property<float>("Historical")
                        .HasColumnType("real");

                    b.Property<float>("Horror")
                        .HasColumnType("real");

                    b.Property<float>("IdolsFemale")
                        .HasColumnType("real");

                    b.Property<float>("IdolsMale")
                        .HasColumnType("real");

                    b.Property<float>("Isekai")
                        .HasColumnType("real");

                    b.Property<float>("Iyashikei")
                        .HasColumnType("real");

                    b.Property<float>("Josei")
                        .HasColumnType("real");

                    b.Property<float>("Kids")
                        .HasColumnType("real");

                    b.Property<float>("LovePolygon")
                        .HasColumnType("real");

                    b.Property<float>("MagicalSexShift")
                        .HasColumnType("real");

                    b.Property<float>("MahouShoujo")
                        .HasColumnType("real");

                    b.Property<float>("MartialArts")
                        .HasColumnType("real");

                    b.Property<float>("Mecha")
                        .HasColumnType("real");

                    b.Property<float>("Medical")
                        .HasColumnType("real");

                    b.Property<float>("Military")
                        .HasColumnType("real");

                    b.Property<float>("Music")
                        .HasColumnType("real");

                    b.Property<float>("Mystery")
                        .HasColumnType("real");

                    b.Property<float>("Mythology")
                        .HasColumnType("real");

                    b.Property<float>("OrganizedCrime")
                        .HasColumnType("real");

                    b.Property<float>("OtakuCulture")
                        .HasColumnType("real");

                    b.Property<float>("Parody")
                        .HasColumnType("real");

                    b.Property<float>("PerformingArts")
                        .HasColumnType("real");

                    b.Property<float>("Pets")
                        .HasColumnType("real");

                    b.Property<float>("Psychological")
                        .HasColumnType("real");

                    b.Property<float>("Racing")
                        .HasColumnType("real");

                    b.Property<float>("Reincarnation")
                        .HasColumnType("real");

                    b.Property<float>("ReverseHarem")
                        .HasColumnType("real");

                    b.Property<float>("Romance")
                        .HasColumnType("real");

                    b.Property<float>("RomanticSubtext")
                        .HasColumnType("real");

                    b.Property<float>("Samurai")
                        .HasColumnType("real");

                    b.Property<float>("School")
                        .HasColumnType("real");

                    b.Property<float>("SciFi")
                        .HasColumnType("real");

                    b.Property<float>("Seinen")
                        .HasColumnType("real");

                    b.Property<long>("SeriesId")
                        .HasColumnType("bigint");

                    b.Property<float>("Shoujo")
                        .HasColumnType("real");

                    b.Property<float>("Shounen")
                        .HasColumnType("real");

                    b.Property<float>("Showbiz")
                        .HasColumnType("real");

                    b.Property<float>("SliceOfLife")
                        .HasColumnType("real");

                    b.Property<float>("Space")
                        .HasColumnType("real");

                    b.Property<float>("Sports")
                        .HasColumnType("real");

                    b.Property<float>("StrategyGame")
                        .HasColumnType("real");

                    b.Property<float>("SuperPower")
                        .HasColumnType("real");

                    b.Property<float>("Supernatural")
                        .HasColumnType("real");

                    b.Property<float>("Survival")
                        .HasColumnType("real");

                    b.Property<float>("Suspense")
                        .HasColumnType("real");

                    b.Property<float>("TeamSports")
                        .HasColumnType("real");

                    b.Property<float>("TimeTravel")
                        .HasColumnType("real");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<float>("UserScore")
                        .HasColumnType("real");

                    b.Property<float>("Vampire")
                        .HasColumnType("real");

                    b.Property<float>("VideoGame")
                        .HasColumnType("real");

                    b.Property<float>("VisualArts")
                        .HasColumnType("real");

                    b.Property<float>("Workplace")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("UserScorings");
                });

            modelBuilder.Entity("MLRecommendator.Database.Models.UserSerie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<byte>("Score")
                        .HasColumnType("smallint");

                    b.Property<long>("SeriesId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserSeries");
                });
#pragma warning restore 612, 618
        }
    }
}
